
'use client'
import './globals.css';
import { useEffect } from 'react';
import type { Metadata } from 'next'
import Cookies from 'js-cookie';
import { checkUserAuthentication } from './Auth'
import Sidebar from './component/sidebar';
const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}
export default function RootLayout({ children }: { children: React.ReactNode }) {
  // const handleSetCookie = () => {
  //   Cookies.set('myCookieName', 'some-value', {
  //     expires: 7,
  //     path: '/',
  //   });
  // };
  // useEffect(() => {
  //   const userIsAuthenticated = checkUserAuthentication();
  //   if (userIsAuthenticated) {
  //     handleSetCookie();
  //     const handleUserRouting = () => {
  //       console.log('Redirecting to dashboard...');
  //       window.location.href = '/dashboard';
  //     };
  //     handleUserRouting();
  //   }
  //   //  else {
  //   //   console.log('User is not authenticated. Redirecting to registration page...');
  //   //   window.location.href = '/registration';
  //   // }
  // }, []);
  return (
    <html lang="en">
        <head>
        {/* <link
          href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap"
          rel="stylesheet"
        /> */}
      </head>
      <body>
        <div className='flex'>
        {children}
        </div>
      </body>
    </html>
  );
}